### ISSUE TITLE
Optimize for Large Amounts

### ISSUE THREAD

**Issue by spencerfinnell** [Astoundify/wp-job-manager-companies#11]
If there are many it should paginate or do one letter at a time.

**Comment by turtlepod** [comment]
This require overhaul of the shortcode.
or maybe create several shortcode for different output system or create shortcode args to load different style.

I don't think it's possible to load the meta value/company name in chunks/offset (?)
(I don't know how to do that in sql, plus i don't think it's that useful)
but currently the calculate post count system is heavy.
And it will always be heavy.

That's why WP  taxonomy/term have a counter system to calculate number of post (object), and it gets reduced/added when we update post/delete post (too complex to duplicate). So, it don't need to query all post (like this plugin did now) to get the total post in that term.
So, the "real" solution is to use custom taxonomy.

But it's possible to reduce query and only load the posts in first found group (letter),
and use the group ("A" -  "Z" + "0-9" ), as pagination. 
and also use transient data to save this cache this query.

**Comment by spencerfinnell** [comment]
https://github.com/Astoundify/wp-job-manager-companies/issues/19#issuecomment-322206961
